version: '3'

volumes:
  mysql-data:
  bundle:
  redis-data:
  es-data:

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379'
    volumes:
      - redis-data:/etc/redis/database

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports: ['9200:9200']

  app:
    image: qcx_api:development
    build:
      context: .
    command: rails server -p 3000 -b '0.0.0.0'
    entrypoint: ./entrypoint
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: 'redis://redis:6379/0'
      ELASTICSEARCH_URL: 'elasticsearch:9200'
    stdin_open: true
    tty: true
    links:
      - db:mysql
      - redis
      - elasticsearch
    depends_on:
      - db
      - redis
      - elasticsearch
